### PR TITLE
Don't panic! on errors; fix apparent bug in JSON value handling

### LINKED ISSUE #2: Don't panic!

### PR DESCRIPTION
**Pull request by lmcmicu**
Closes #2

### CODE REVIEW

File: src/hiccup.rs [hunk 1]
```diff
@@ -126,7 +137,22 @@ pub fn render_by_depth(element: &Value, depth: usize) -> String {
                     if key.eq("checked") {
                         output = format!("{} {}", output, key);
                     } else {
-                        output = format!("{} {}=\"{}\"", output, key, value.as_str().unwrap());
+                        output = format!(
+                            "{} {}=\"{}\"",
+                            output,
+                            key,
+                            match value {
+                                Value::String(s) => s.as_str().to_string(),
```
Comment (ckindermann) [inline src/hiccup.rs]: Why `s.as_str().to_string()`? Don't we just want `s`?

**Review by ckindermann — APPROVED** [review]
Looks good to me! (Though I still maintain that the conversion from different data types to String is not a bug fix but a feature addition supporting some syntactic sugar for hiccup.)

File: src/hiccup.rs (hunk 1 above)
Comment (lmcmicu) [reply src/hiccup.rs]: Yes you're right. We don't need those calls to `.as_str().to_string()`.

Regarding whether it's a bug or a feature request: Sure, you can call it whatever you like :-) From my point of view I would just like this library to support the same inputs as the python version :-)

**Review by jamesaoverton — APPROVED** [review]
